import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Web Predict Niave & ID3",
  icons : "/favicon.ico",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
